#!/bin/sh
set -eu

# First-run setup for a dedicated HA Smartdash nginx virtual host. Values may
# be supplied as SMARTDASH_* environment variables for Docker/Unraid.
say() { printf '%s\n' "$*"; }
fail() { say "FEJL: $*" >&2; exit 1; }

prompt() {
  prompt_name=$1; prompt_text=$2; prompt_default=$3
  eval "prompt_value=\${$prompt_name:-}"
  if [ -z "$prompt_value" ]; then
    if [ ! -t 0 ]; then prompt_value=$prompt_default
    else
      printf '%s [%s]: ' "$prompt_text" "$prompt_default"
      IFS= read -r prompt_value
      prompt_value=${prompt_value:-$prompt_default}
    fi
    case "$prompt_name" in
      SMARTDASH_HA_URL) SMARTDASH_HA_URL=$prompt_value ;;
      SMARTDASH_WEB_ROOT) SMARTDASH_WEB_ROOT=$prompt_value ;;
      SMARTDASH_NGINX_CONF) SMARTDASH_NGINX_CONF=$prompt_value ;;
      SMARTDASH_LISTEN_PORT) SMARTDASH_LISTEN_PORT=$prompt_value ;;
      SMARTDASH_SERVER_NAME) SMARTDASH_SERVER_NAME=$prompt_value ;;
      SMARTDASH_PHP_UPSTREAM) SMARTDASH_PHP_UPSTREAM=$prompt_value ;;
      *) fail "Ukendt opsætningsfelt: $prompt_name" ;;
    esac
  fi
}

prompt SMARTDASH_HA_URL "Home Assistant intern URL" "http://homeassistant.local:8123"
prompt SMARTDASH_WEB_ROOT "Smartdash webrod" "/var/www/ha-smartdash"
prompt SMARTDASH_NGINX_CONF "Aktiv Nginx serverfil" "/etc/nginx/conf.d/ha-smartdash.conf"
prompt SMARTDASH_LISTEN_PORT "Smartdash HTTP-port" "80"
prompt SMARTDASH_SERVER_NAME "Nginx server_name" "_"
prompt SMARTDASH_PHP_UPSTREAM "PHP-FPM upstream" "unix:/run/php/php-fpm.sock"

case "$SMARTDASH_HA_URL" in http://*|https://*) ;; *) fail "HA URL skal begynde med http:// eller https://" ;; esac
case "$SMARTDASH_LISTEN_PORT" in ''|*[!0-9]*) fail "HTTP-porten skal være et tal" ;; esac
for config_value in "$SMARTDASH_HA_URL" "$SMARTDASH_WEB_ROOT" "$SMARTDASH_NGINX_CONF" "$SMARTDASH_SERVER_NAME" "$SMARTDASH_PHP_UPSTREAM"; do
  case "$config_value" in *';'*|*'{'*|*'}'*) fail "Opsætningsværdier må ikke indeholde semikolon eller krøllede parenteser" ;; esac
done
HA_UPSTREAM=${SMARTDASH_HA_URL%/}
CONF_DIR=$(dirname "$SMARTDASH_NGINX_CONF")
[ -d "$CONF_DIR" ] || mkdir -p "$CONF_DIR"
TMP_CONF="${SMARTDASH_NGINX_CONF}.new.$$"
trap 'rm -f "$TMP_CONF"' EXIT HUP INT TERM

cat > "$TMP_CONF" <<EOF
# Generated by HA Smartdash deploy/setup-smartdash.sh
server {
    listen ${SMARTDASH_LISTEN_PORT};
    server_name ${SMARTDASH_SERVER_NAME};
    root ${SMARTDASH_WEB_ROOT};
    index index.html;
    location / { try_files \$uri \$uri/ /index.html; }
    location ~ \.php\$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_pass ${SMARTDASH_PHP_UPSTREAM};
    }
    location = /ha { return 301 /ha/; }
    location /ha/ {
        proxy_pass ${HA_UPSTREAM}/;
        proxy_http_version 1.1;
        proxy_set_header Host \$proxy_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_read_timeout 3600s;
    }
    location ~ ^/(data|\.git)/ { deny all; return 404; }
}
EOF

BACKUP=
if [ -f "$SMARTDASH_NGINX_CONF" ]; then
  BACKUP="${SMARTDASH_NGINX_CONF}.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$SMARTDASH_NGINX_CONF" "$BACKUP"
  say "Backup gemt: $BACKUP"
fi
mv "$TMP_CONF" "$SMARTDASH_NGINX_CONF"
trap - EXIT HUP INT TERM
say "Nginx-konfiguration skrevet: $SMARTDASH_NGINX_CONF"

if command -v nginx >/dev/null 2>&1; then
  if ! nginx -t; then
    if [ -n "$BACKUP" ]; then
      cp "$BACKUP" "$SMARTDASH_NGINX_CONF"
      say "Den tidligere Nginx-konfiguration er automatisk gendannet."
    else
      mv "$SMARTDASH_NGINX_CONF" "${SMARTDASH_NGINX_CONF}.invalid"
      say "Den ugyldige fil er flyttet til ${SMARTDASH_NGINX_CONF}.invalid."
    fi
    fail "nginx -t fejlede; den nye konfiguration blev ikke aktiveret"
  fi
  if [ "${SMARTDASH_RELOAD_NGINX:-1}" = "1" ]; then nginx -s reload; say "Nginx er genindlæst."; fi
else
  say "Nginx findes ikke her; valider/genindlæs den aktive container efterfølgende."
fi

SMARTDASH_PUBLIC_URL=${SMARTDASH_PUBLIC_URL:-"http://127.0.0.1:${SMARTDASH_LISTEN_PORT}"}
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
if command -v curl >/dev/null 2>&1; then
  say "Tester Home Assistant-loginproxy..."
  sh "$SCRIPT_DIR/check-install.sh" "$SMARTDASH_PUBLIC_URL" || {
    say "HTTP 400 betyder normalt, at HA mangler Nginx-IP'en under http.trusted_proxies."
    exit 1
  }
else say "curl findes ikke; proxytesten blev sprunget over."
fi
say "Opsætningen er færdig. Åbn ${SMARTDASH_PUBLIC_URL%/}/admin/"
