const viewName=new URLSearchParams(location.search).get('view')||'energy';
const roomData=[['Living room','⌂','22.3 °C','45%'],['Kitchen','◫','21.8 °C','43%'],['Office','▤','22.0 °C','41%'],['Bedroom','☾','20.4 °C','48%'],['Bathroom','◉','23.1 °C','52%'],['Workshop','◇','19.8 °C','39%']];
const views={
 rooms:{title:'Rooms',sub:'Climate and controls across the home',html:`<div class="rooms span12">${roomData.map(x=>`<article class="card room"><div class="icon">${x[1]}</div><b>${x[0]}</b><strong>${x[2]}</strong><div class="muted">Humidity ${x[3]} · Lights off</div></article>`).join('')}</div>`},
 energy:{title:'Energy',sub:'Consumption and production',html:`<article class="card span4"><div class="muted">Consumption now</div><div class="metric">1.84 kW</div><div style="color:#64e4ac">↓ 12% from yesterday</div></article><article class="card span4"><div class="muted">Solar production</div><div class="metric">3.26 kW</div><div style="color:#ffd767">2.1 kW exported</div></article><article class="card span4"><div class="muted">Today</div><div class="metric">14.7 kWh</div><div class="muted">Estimated cost €3.42</div></article><article class="card span8"><h2>Power today</h2><div class="line"><svg viewBox="0 0 800 220" preserveAspectRatio="none"><path d="M0 175 C90 150 100 180 190 130 S330 155 410 88 S550 115 620 65 S730 85 800 40" fill="none" stroke="#61ddff" stroke-width="6"/><path d="M0 195 C110 190 120 135 230 155 S360 105 460 130 S610 70 800 92" fill="none" stroke="#ffd55e" stroke-width="5"/></svg></div></article><article class="card span4"><h2>Last 7 days</h2><div class="chart">${[48,67,55,82,74,94,63].map(h=>`<div class="bar" style="height:${h}%"></div>`).join('')}</div></article>`},
 weather:{title:'Weather',sub:'Forecast and readable radar',html:`<article class="card span7"><h2>Precipitation radar</h2><div class="radar"></div></article><article class="card span5"><div class="muted">Outside now</div><div class="metric">21.4 °C</div><div>Clear sky · feels like 20.8 °C</div><p class="muted">Wind 3.2 m/s · Humidity 58% · UV 4</p><div class="forecast">${['Fri','Sat','Sun','Mon','Tue','Wed'].map((d,i)=>`<div class="day"><b>${d}</b><div class="sun"></div><strong>${21+i%3}°</strong><div class="muted">${13+i%2}°</div></div>`).join('')}</div></article>`},
 robot:{title:'Robot vacuum',sub:'Controls assembled from the selected device',html:`<article class="card span7 device"><div class="robot"></div><div><div class="muted">Selected device</div><div class="metric">Ground floor robot</div><div style="color:#66e5ac">● Docked · 92%</div><p class="muted">Last cleaned 86 m² in 74 minutes</p></div></article><article class="card span5"><h2>Available controls</h2><div class="controls"><div class="control"><b>▶ Start</b><div class="muted">Full clean</div></div><div class="control"><b>⌂ Dock</b><div class="muted">Return home</div></div><div class="control"><b>Ⅱ Pause</b><div class="muted">Current task</div></div><div class="control"><b>◎ Locate</b><div class="muted">Play sound</div></div><div class="control"><b>Kitchen</b><div class="muted">Area clean</div></div><div class="control"><b>Living room</b><div class="muted">Area clean</div></div></div></article>`},
 pool:{title:'Pool & vehicle',sub:'Optional pages adapt to the entities you configure',html:`<article class="card span7"><h2>Pool status</h2><div class="pool">${[15,25,35,48,63,76,88].map((x,i)=>`<i class="bubble" style="left:${x}%;width:${10+i%3*5}px;height:${10+i%3*5}px;animation-delay:-${i*.55}s"></i>`).join('')}</div><div class="metric">28.2 °C</div><div style="color:#63e3ad">Water clear · No person detected · Pump running</div></article><article class="card span5"><h2>Electric vehicle</h2><div class="battery"><div class="liquid"></div></div><div class="metric">78%</div><div style="color:#67e5ae">Charging · 48 minutes remaining</div><p class="muted">Estimated range 326 km</p></article>`}
};
document.querySelectorAll('.tabs a').forEach(a=>a.classList.toggle('active',a.href.includes('='+viewName)));
const view=views[viewName]||views.energy;document.querySelector('#title').textContent=view.title;document.querySelector('#subtitle').textContent=view.sub;document.querySelector('#content').innerHTML=view.html;document.title='HA Smartdash — '+view.title+' demo';
